### PR TITLE
Override $_SERVER params via annotation

### PR DESCRIPTION
**Pull request by tschreiner**
This commit allows to pass $_SERVER parameters to be overwritten in the Legacy Request.

Example use: Legacy app needs specific URL in $_SERVER super variable for its routing.

Usage:
@Legacy\Dispatch(server={"REQUEST_URI"="/legacy/app/route"})

### CODE REVIEW

**Comment by mpdude** [comment]
Somehow that seems familiar and I think we have a very similar solution already working in one of our legacy-integrated projects... @MalteWunsch do you remember what it was?

**Comment by tschreiner** [comment]
> The advantage over an annotation is that it can be based on actual request data.

Yep, that's exactly the problem. We need a complete independent mapping of sf2 routes to the legacy routes/actions. Of course you could do that in the legacy front controller, but in our case that's too inflexible. We find it easier to do it via an annotation.

**Comment by mpdude** [comment]
Hey @tschreiner,

sorry for getting back to this so late. 

This way of messing around with the `$_SERVER` variable is really ugly and so we're unsure whether it is a good idea to add it (and possibly having to support it in the future). This would also raise the question whether we should also support changing `$_GET`, `$_REQUEST` and so on.

Of course I know that there are no rules when it comes to integrating legacy code and you can hardly  get away with "beautiful" solutions.

But I'd be much happier if we could find a way that makes this bundle more flexible so you _can_ apply this solution if you consider it necessary, without having it in the bundle's code in an explicit way.

Probably I still need to understand your use case better... So, why can't you do the `$_SERVER` tweaking in your legacy bootstrap / front controller file (or an additional wrapper around it) just based on the `request` passed in?

Can you give an example of the values you need to change and why they depend on the controller (because that's where the annotaion lives) and not the request data?

Thanks!

**Comment by tschreiner** [comment]
I think this can be closed.

**Pull request closed without merging**
